//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Air.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class airEntities : DbContext
    {
        private static airEntities _context;
        public static airEntities GetContext()
        {
            if (_context == null)
                _context = new airEntities();
            return _context;
        }
        public airEntities()
            : base("name=airEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<aircraft> aircraft { get; set; }
        public virtual DbSet<Aircraft_crews> Aircraft_crews { get; set; }
        public virtual DbSet<Staff> Staff { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Ticket_sales> Ticket_sales { get; set; }
        public virtual DbSet<Departure_schedule> Departure_schedule { get; set; }
        public virtual DbSet<Table1> Table1 { get; set; }
    }
}
