//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Air.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Staff
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Staff()
        {
            this.Table1 = new HashSet<Table1>();
        }
    
        public int id_st { get; set; }
        public string syrname { get; set; }
        public string name { get; set; }
        public string patronumic { get; set; }
        public System.DateTime date { get; set; }
        public System.DateTime date_work { get; set; }
        public string experience { get; set; }
        public string floor { get; set; }
        public string address { get; set; }
        public string city { get; set; }
        public string phone { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Table1> Table1 { get; set; }
    }
}
