//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Air.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table1
    {
        public int id_st { get; set; }
        public int id_air { get; set; }
        public int id_cr { get; set; }
    
        public virtual aircraft aircraft { get; set; }
        public virtual Aircraft_crews Aircraft_crews { get; set; }
        public virtual Staff Staff { get; set; }
    }
}
