//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Air.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket_sales
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ticket_sales()
        {
            this.Departure_schedule = new HashSet<Departure_schedule>();
        }
    
        public int id_tic { get; set; }
        public System.DateTime date { get; set; }
        public string SNP { get; set; }
        public string Ps { get; set; }
        public string nomber { get; set; }
        public int quant { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Departure_schedule> Departure_schedule { get; set; }
    }
}
